prog/config/routes.rb
Prog::Application.routes.draw do
  resources :telephones

end

prog/app/models/telephone.rb
class Telephone < ActiveRecord::Base
  attr_accessible :Address, :name, :phoneno, :city
end

prog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

prog/app/controllers/telephones_controller.rb
class TelephonesController < ApplicationController
  # GET /telephones
  # GET /telephones.json
  def index


if params[:commit]=="search" && params[:q]=='' && (params[:a]=="0" ||params[:a]=="1"||params[:a]=="2")

  	 @telephones = Telephone.all

elsif params[:a]=="2" && params[:a]=="0"

     	@telephones=Telephone.where(" name LIKE ? ", "#{params[:q]}%")

elsif params[:a]=="1" 

	@telephones=Telephone.where("name = ?", params[:q])

else
	@telephones=Telephone.where("name = ?", params[:q])

end


   respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @telephones }
    end
  end

  # GET /telephones/1
  # GET /telephones/1.json
  def show
    @telephone = Telephone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @telephone }
    end
  end

  # GET /telephones/new
  # GET /telephones/new.json
  def new
    @telephone = Telephone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @telephone }
    end
  end

  # GET /telephones/1/edit
  def edit
    @telephone = Telephone.find(params[:id])
  end

  # POST /telephones
  # POST /telephones.json
  def create
    @telephone = Telephone.new(params[:telephone])

    respond_to do |format|
      if @telephone.save
        format.html { redirect_to @telephone, notice: 'Telephone was successfully created.' }
        format.json { render json: @telephone, status: :created, location: @telephone }
      else
        format.html { render action: "new" }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /telephones/1
  # PUT /telephones/1.json
  def update
    @telephone = Telephone.find(params[:id])

    respond_to do |format|
      if @telephone.update_attributes(params[:telephone])
        format.html { redirect_to @telephone, notice: 'Telephone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telephones/1
  # DELETE /telephones/1.json
  def destroy
    @telephone = Telephone.find(params[:id])
    @telephone.destroy

    respond_to do |format|
      format.html { redirect_to telephones_url }
      format.json { head :no_content }
    end
  end
end

prog/app/helpers/application_helper.rb
module ApplicationHelper
end

prog/app/helpers/telephones_helper.rb
module TelephonesHelper
end

prog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

prog/app/views/telephones/_form.html.erb
<%= form_for(@telephone) do |f| %>
  <% if @telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telephone.errors.count, "error") %> prohibited this telephone from being saved:</h2>

      <ul>
      <% @telephone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Address %><br />
    <%= f.text_area :Address %>
  </div>
  <div class="field">
    <%= f.label :phoneno %><br />
    <%= f.text_field :phoneno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prog/app/views/telephones/edit.html.erb
<h1>Editing telephone</h1>

<%= render 'form' %>

<%= link_to 'Show', @telephone %> |
<%= link_to 'Back', telephones_path %>

prog/app/views/telephones/index.html.erb
<h1>Listing telephones</h1>

<%=form_tag("/telephones", :method => "get") do %>
 Search Key: <%=text_field_tag :q, params[:q]%>
 Match:<%= select_tag(:a, options_for_select([['--select--',0],['Exact', 1],['Startwith', 2]]))%>
 <%=submit_tag ("search")%>
<%end%>




<table>
  <tr>
    <th>Phoneno</th>
    <th>Name</th>
    <th>Address</th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @telephones.each do |telephone| %>
  <tr>
    <td><%= telephone.phoneno %></td>
    <td><%= telephone.name %></td>
    <td><%= telephone.Address %></td>
    <td><%= link_to 'Show', telephone %></td>
    <td><%= link_to 'Edit', edit_telephone_path(telephone) %></td>
    <td><%= link_to 'Destroy', telephone, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Telephone', new_telephone_path %>

prog/app/views/telephones/new.html.erb
<h1>New telephone</h1>

<%= render 'form' %>

<%= link_to 'Back', telephones_path %>

prog/app/views/telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @telephone.name %>
</p>

<p>
  <b>Address:</b>
  <%= @telephone.Address %>
</p>

<p>
  <b>Phoneno:</b>
  <%= @telephone.phoneno %>
</p>


<%= link_to 'Edit', edit_telephone_path(@telephone) %> |
<%= link_to 'Back', telephones_path %>